version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0"]